# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-06 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsearch', '0002_auto_20201106_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='bloodg',
            new_name='blood_group',
        ),
    ]
